###
GET http://localhost:4000/boughtcourse/all
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OSwicm9sZSI6IlVTRVIiLCJpYXQiOjE1OTg0ODMzNTV9.d0epdo8ZZWvRWFUTcfCFwJFfNFSlnNxHFqnY4vdrrbw

###
POST http://localhost:4000/boughtcourse/4
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Miwicm9sZSI6IlVTRVIiLCJpYXQiOjE1OTk3NzkxMzl9.N37is-H1utEj1xOAOo5Z7hrsEl7Eth5hzyQ7mJR8erQ

###
POST http://localhost:4000/boughtcourse/2/review
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Miwicm9sZSI6IlVTRVIiLCJpYXQiOjE1OTk3NzkxMzl9.N37is-H1utEj1xOAOo5Z7hrsEl7Eth5hzyQ7mJR8erQ
Content-Type: application/json

{
    "review":3,
    "reviewMessage":"It's very good!",
    "authorName":"Vadim Moiseenko"
}