###
GET http://localhost:4000/boughtcourse/all

###
POST http://localhost:4000/boughtcourse/7
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OSwicm9sZSI6IlVTRVIiLCJpYXQiOjE1OTg0ODMzNTV9.d0epdo8ZZWvRWFUTcfCFwJFfNFSlnNxHFqnY4vdrrbw