### with Admin permissions
GET http://localhost:3000/allCourses
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjEsInJvbGUiOiJBRE1JTiIsImlhdCI6MTU5NTkzNzgxNn0.N_xHFlBxZc1HDp4MBXC9kvoi_9zk0wswQccfStbBkZ4

### without Admin permissions
GET http://localhost:3000/allCourses
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjIsImlhdCI6MTU5NTkzNTE1N30.6SEJdD6mg24poMccmTtOrkEuafS-iXMFyf_qZKG5Y9c

# ### get Curruculum
# GET http://localhost:3000/courses/curriculum/1
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjIsImlhdCI6MTU5NTkzNTE1N30.6SEJdD6mg24poMccmTtOrkEuafS-iXMFyf_qZKG5Y9c


### Get publish courses 
GET http://localhost:3000/courses

### GET popular courses 
GET http://localhost:3000/popularCourses

### GET course by id
GET http://localhost:3000/coursePublic/11

### GET my own course by id not OWNER
# GET http://localhost:3000/coursePublic/11
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjIsInJvbGUiOiJVU0VSIiwiaWF0IjoxNTk1OTQzNTc3fQ.LgwNwnTHhLYmcKHlC5UhZuq6Q07UQLuGBw_19wqIix0

### GET my own course by id by OWNER
GET http://localhost:3000/myOwnCourses/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjEsInJvbGUiOiJBRE1JTiIsImlhdCI6MTU5NTk0MzM3MX0.Z7slCEMYmombKVL5dHvS2u3A1gNGMUVwPCGeYZXb5xE
### GET my own course by id by OWNER
GET http://localhost:3000/myBoughtCourse/9
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjMsInJvbGUiOiJVU0VSIiwiaWF0IjoxNTk1OTQ4NTc1fQ.4nd8XFIrbRzMDj5imGAuZeG2tPSDmeqFVfRg_wX9r-4

### Publish course
POST http://localhost:3000/publishCourse/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjYsInJvbGUiOiJBRE1JTiIsImlhdCI6MTU5NTk1ODc1Mn0.KKIZAZqXH49sgL1UiDeRq5CP9irsbMq-Q5RhpAFpWOA
Content-Type: application/json

{
    "status":"PUBLISH"
}

### Create coures who has teacher profile
POST http://localhost:3000/course
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjEsInJvbGUiOiJBRE1JTiIsImlhdCI6MTU5NTk0MzM3MX0.Z7slCEMYmombKVL5dHvS2u3A1gNGMUVwPCGeYZXb5xE

### Create coures who has no teacher account
POST http://localhost:3000/course
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjIsInJvbGUiOiJVU0VSIiwiaWF0IjoxNTk1OTU0Mjk3fQ.tNLmHM546dNNdqD9LHXlAYLg-sMg_Rh-zZPu0mlCqEA

### Buy course 
POST http://localhost:3000/buyCourse/9
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjMsInJvbGUiOiJVU0VSIiwiaWF0IjoxNTk1OTQ4NTc1fQ.4nd8XFIrbRzMDj5imGAuZeG2tPSDmeqFVfRg_wX9r-4

### Delete course by owner 
DELETE http://localhost:3000/course/9
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjEsInJvbGUiOiJVU0VSIiwiaWF0IjoxNTk1OTU5MDA2fQ.BeGr1dbazOj3GO4o2d6IAb-LabNulb6OxKnQd2i_Xs0

### Delete course by admin
DELETE http://localhost:3000/course/10
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjYsInJvbGUiOiJBRE1JTiIsImlhdCI6MTU5NTk1ODc1Mn0.KKIZAZqXH49sgL1UiDeRq5CP9irsbMq-Q5RhpAFpWOA

### Update info
PATCH http://localhost:3000/course/14
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjEsInJvbGUiOiJVU0VSIiwiaWF0IjoxNTk1OTU5MDA2fQ.BeGr1dbazOj3GO4o2d6IAb-LabNulb6OxKnQd2i_Xs0
Content-Type: application/json

{
    "name":"I love my course very much ",
    "forSearchEngines":440,
    "totalPurchase":354,
    "price":25
}