GET http://localhost:4000/payment/

###

GET https://api.sandbox.paypal.com/v2/payments/authorizations/sb-9ivfq2752664
Content-Type: application/json
Authorization: Basic AWM3oXkuKBMhbcQSbv_xLHNnW2A87k1cpq1olxcZyQYL7RzC0W9ACuXoNNEYw2AB6VZx0lywS_bfBo2b:ED5DQ4-hMFbN1igpo_yqNpE4D59sK86C5CuAP3fmU88nO47xbPVQyEQ1wYp-h4763rbXla8Fez8QkGBL

###
POST https://api.sandbox.paypal.com/v1/oauth2/token
Content-Type: application/json
Accept-Language: "en_US"
Authorization: Basic AcKBt7lr_UgmiD9FJY6II7FQEPslK6sg-hKqdIo2PMazineptAtEWO_pxXC-TFu9RNNdAlVkeRBbTEs6:EOJvrHGIP2dvucNtlZdVYGrJZH5TYKSLDktWpSIe-5AALs8kI9uwbhEd_m04x0HKtkK6gcNx18yMUQ1Y
{
    "grant_type":"client_credentials"
}

### 
POST https://api.sandbox.paypal.com/v2/checkout/orders
Content-Type: application/json
# Authorization: Basic AcKBt7lr_UgmiD9FJY6II7FQEPslK6sg-hKqdIo2PMazineptAtEWO_pxXC-TFu9RNNdAlVkeRBbTEs6:EOJvrHGIP2dvucNtlZdVYGrJZH5TYKSLDktWpSIe-5AALs8kI9uwbhEd_m04x0HKtkK6gcNx18yMUQ1Y
Authorization: Basic AWM3oXkuKBMhbcQSbv_xLHNnW2A87k1cpq1olxcZyQYL7RzC0W9ACuXoNNEYw2AB6VZx0lywS_bfBo2b:ED5DQ4-hMFbN1igpo_yqNpE4D59sK86C5CuAP3fmU88nO47xbPVQyEQ1wYp-h4763rbXla8Fez8QkGBL


{
  "intent": "CAPTURE",
  "purchase_units": [
    {
      "amount": {
        "currency_code": "RUB",
        "value": "100.00"
      }
    }
  ]
}

###
GET https://api.sandbox.paypal.com/v2/checkout/orders/7M450553B6139622P
Authorization: Basic AWM3oXkuKBMhbcQSbv_xLHNnW2A87k1cpq1olxcZyQYL7RzC0W9ACuXoNNEYw2AB6VZx0lywS_bfBo2b:ED5DQ4-hMFbN1igpo_yqNpE4D59sK86C5CuAP3fmU88nO47xbPVQyEQ1wYp-h4763rbXla8Fez8QkGBL
