### GET all users Must be blocked Good
GET http://localhost:3000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjYsInJvbGUiOiJBRE1JTiIsImlhdCI6MTU5NTk1ODc1Mn0.KKIZAZqXH49sgL1UiDeRq5CP9irsbMq-Q5RhpAFpWOA
### Me as Admin
GET http://localhost:3000/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjYsInJvbGUiOiJBRE1JTiIsImlhdCI6MTU5NTk1ODc1Mn0.KKIZAZqXH49sgL1UiDeRq5CP9irsbMq-Q5RhpAFpWOA

### Me as User
GET http://localhost:3000/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjEsInJvbGUiOiJVU0VSIiwiaWF0IjoxNTk1OTU5MDA2fQ.BeGr1dbazOj3GO4o2d6IAb-LabNulb6OxKnQd2i_Xs0

### Registation
POST http://localhost:4000/signup
Content-Type: application/json

{
    "password":3524,
    "email":"admin@admin.ru"
}


### Login as Admin
POST http://localhost:3000/login 
Content-Type: application/json

{
    "password":"3524",
    "email":"admin@admin.ru"
}

### Login as User
POST http://localhost:3000/login 
Content-Type: application/json

{
    "password":"35243524",
    "email":"ya@yandex.ru"
}

