POST http://localhost:4000/video/video
Content-Type: application/json

{
    "size":34532
}
###
DELETE http://localhost:4000/video/464504791/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6IlRFQUNIRVIiLCJpbnN0cnVjdG9ySWQiOjEsImlhdCI6MTYwMTcwODk0NH0.bs9Cpgycf6W0_S3tR2YTo1youdrFqVK9lx1u5gHmI1o

###
PATCH http://localhost:4000/buildcourse/photo

### 
PUT http://chess-courses.hb.bizmrg.com/course/image5?AWSAccessKeyId=8w1tDW9mDGyYNg6YAT4gnA&Content-Type=jpeg&Expires=1601830334&Signature=aRQFiFke80DjRyCOfhVai7LyORw%3D