GET http://localhost:4000/yandex/payment?token=eyJ0eXBlIjoiY2hlY2tvdXRfanNfYmFua19jYXJkIiwiZW5jcnlwdGVkIjoiSCtBNDREZWVBVlJSWlBLcFpLT0Q5Z0VlS0VuTEtPM2JvMklLM0R4Vjd6MWkycVlXeVZYdFFIakFhdGNxNGt2S1QxSTBPM3R6WGZvSFU2ME9aMW0za1UzZXlJeGwxZU5wV0czWlptM3J2TmI4RXhuclgrc0JRR0Ewbmg1amtyclloR2IxUWNUSkFNeXp6NnRQdTN5RTNWTkpjbXNSZGwzTE5zM1RpZU5KYzRvMjlmMDZhTmo3NGlNaFV2TDlOM3hDc25CZWtnPT0iLCJpbml0VmVjdG9yIjoiTklOMTN2cnI3RzRGK0xsU3MrcjlNQT09Iiwia2V5SWQiOiJPak5BQmsvbVRqbmRMa1ZmVHVTUXR3PT0ifQ==
